### ISSUE TITLE
Security Audit

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#1943]
- [x] [ADA-ARGO-SA-10: #1944] 
- [x] [ADA-ARGO-SA-12: #1946] 
- [x] [ADA-ARGO-SA-13: #1947] 
- [x] [ADA-ARGO-SA-17: #1949] 
- [x] [ADA-ARGO-SA-18: #1950] 
- [x] [ADA-ARGO-SA-20: #1952]
- [x] [ADA-ARGO-SA-21: #1953]
- [x] [ADA-ARGO-SA-22: #1954]
- [x] [ADA-ARGO-SA-23: #1955]
- [x] [ADA-ARGO-SA-24: #1956]
- [x] [ADA-ARGO-SA-25: #1957]
